pods:
  - name: front-end-pod
    labels:
      - front-end
    replicas: 2
    storage: 10000
    prefix: front-end
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: orders-request-pod
    labels:
      - orders
    replicas: 2
    storage: 10000
    prefix: orders-request
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: orders-db-pod
    labels:
      - orders
    replicas: 3
    storage: 5000
    prefix: orders-db
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: carts-pod
    labels:
      - carts
    replicas: 1
    storage: 5000
    prefix: carts
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: rabbitmq
    labels:
     - rabbitmq
    replicas: 1
    storage: 5000
    prefix: rabbitmq
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: catalogue
    labels:
    - catalogue
    replicas: 1
    storage: 5000
    prefix: catalogue
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: queue-master
    labels:
      - queue-master
    replicas: 1
    storage: 5000
    prefix: queue
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100

  - name: payment
    labels:
      - payment
    replicas: 1
    storage: 5000
    prefix: payment
    containers:
      - size: 1000
        pes: 1
        mips: 1000
        ram: 64
        bw: 100